language: python

python:
  - "3.4"

before_install:
  - wget http://ftp.gnu.org/gnu/glpk/glpk-4.55.tar.gz
  - tar vxfz glpk-4.55.tar.gz
  - cd glpk-4.55 && ./configure --prefix=/usr && make && make install

install:
  - pip install -e .

script:
  - "python tests/test_glpk.py"

